"""
🧠  Advisor — Pre-Flight Advisory Report Generator
====================================================
Vayne Consulting — Smart Scout Multi-Industry Edition

Generates a strategic market brief for a given industry BEFORE
any individual outreach is built. This is the "collect and advise" phase.

The report answers:
  1. What are the dominant weaknesses in this vertical right now?
  2. What framing will resonate most with this audience?
  3. What 3 things should the scout prioritize detecting?
  4. What is the strongest opening move for Vayne Consulting in this space?

Output: reports/{slug}/advisory_{date}.md

Usage:
    from config_loader import load_industry
    from advisor import generate_advisory

    config = load_industry("law_firms")
    report = generate_advisory(config, client=openai_client)
    print(report.markdown)
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

try:
    from openai import OpenAI
except ImportError:
    print("[!] Missing dependency: openai")
    print("    Run: pip install openai")
    sys.exit(1)

from config_loader import IndustryConfig


REPORTS_BASE = Path(__file__).parent / "reports"


@dataclass
class AdvisoryReport:
    """Structured output of the pre-flight advisory generation."""
    industry_name: str
    industry_slug: str
    generated_at: str
    custom_notes: str
    market_brief: str           # LLM narrative overview
    top_weaknesses: list[str]   # Structured list
    resonance_framing: str      # How to position the pitch
    scout_priorities: list[str] # What to look for in audits
    opening_move: str           # Recommended first action

    @property
    def markdown(self) -> str:
        """Render the advisory as a formatted Markdown document."""
        weaknesses_md = "\n".join(f"- {w}" for w in self.top_weaknesses)
        priorities_md = "\n".join(f"{i+1}. {p}" for i, p in enumerate(self.scout_priorities))
        notes_block = f"\n> **Custom Notes**: {self.custom_notes}\n" if self.custom_notes else ""

        return f"""# 🎯 Smart Scout Advisory Report
## Industry: {self.industry_name}
**Generated**: {self.generated_at}
{notes_block}
---

## Executive Summary

{self.market_brief}

---

## Top Weaknesses in This Vertical

{weaknesses_md}

---

## Resonance Frame (How to Position the Offer)

{self.resonance_framing}

---

## Scout Priorities (What to Detect in Audits)

{priorities_md}

---

## Recommended Opening Move

{self.opening_move}

---

*Generated by Smart Scout — Vayne Consulting Liquidity Acceleration Tool*
"""


ADVISORY_SYSTEM_PROMPT = """\
You are a strategic market intelligence analyst for a boutique consulting firm.
Your job is to produce a concise, actionable pre-flight brief before a targeted
outreach campaign is launched for a specific industry vertical.

You will receive:
- The industry name and its common pain points
- The key trust signals their clients look for
- The consulting firm's offer angle for this vertical

Return your analysis as a structured JSON object with EXACTLY these keys:
{
  "market_brief": "2-3 sentence narrative overview of the current state of this industry's digital presence",
  "top_weaknesses": ["weakness 1", "weakness 2", "weakness 3", "weakness 4"],
  "resonance_framing": "1-2 sentences on how to frame the consulting offer to resonate with decision makers in this industry",
  "scout_priorities": ["specific thing to detect 1", "specific thing to detect 2", "specific thing to detect 3"],
  "opening_move": "1 specific, concrete first action to take when entering this vertical (e.g., target niche, channel, message angle)"
}

Be specific, punchy, and strategic. Avoid generic consulting speak.
Think like a predatory intelligence analyst, not a polite advisor.
"""


def generate_advisory(
    config: IndustryConfig,
    client: Optional[OpenAI] = None,
    model: str = "gpt-4o"
) -> AdvisoryReport:
    """
    Generate a pre-flight advisory report for the given industry config.

    Args:
        config:  Loaded IndustryConfig dataclass
        client:  OpenAI client instance (creates one from env if None)
        model:   LLM model to use (default: gpt-4o)

    Returns:
        AdvisoryReport dataclass with .markdown property for file output
    """
    import json

    if client is None:
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
            raise EnvironmentError(
                "[!] OPENAI_API_KEY not set. Add it to your .env file."
            )
        client = OpenAI(api_key=api_key)

    # Build the user prompt from the industry config
    pain_points_str = "\n".join(f"- {p}" for p in config.pain_points)
    trust_signals_str = "\n".join(f"- {t}" for t in config.trust_signals)

    user_prompt = f"""
Industry: {config.name}

Common pain points in this vertical:
{pain_points_str}

Trust signals clients look for:
{trust_signals_str}

Our offer angle for this vertical:
{config.offer_angle}

Analysis focus for the scout:
{config.analysis_focus}

Additional custom notes for this run:
{config.custom_notes or "None provided."}
"""

    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": ADVISORY_SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.6,
            max_tokens=800,
            response_format={"type": "json_object"}
        )

        raw = response.choices[0].message.content.strip()
        data = json.loads(raw)

    except Exception as e:
        # Fallback: return a config-derived report without LLM
        print(f"[!] LLM Advisory generation failed: {e}")
        print("    Falling back to config-derived advisory...")
        data = {
            "market_brief": (
                f"{config.name} businesses frequently have outdated digital presences "
                f"that fail to reflect the quality of their services. "
                f"Key gaps include: {config.pain_points[0].lower()} and {config.pain_points[1].lower()}."
            ),
            "top_weaknesses": config.pain_points[:4],
            "resonance_framing": config.outreach_angle,
            "scout_priorities": [
                ind for ind in config.priority_indicators.get("high", [])[:3]
            ],
            "opening_move": (
                f"Start with {config.locations[0]} — run Niche Builder for "
                f"'{config.search_keywords[0]}' and audit the top 20 results."
            )
        }

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    report = AdvisoryReport(
        industry_name=config.name,
        industry_slug=config.slug,
        generated_at=generated_at,
        custom_notes=config.custom_notes,
        market_brief=data.get("market_brief", ""),
        top_weaknesses=data.get("top_weaknesses", []),
        resonance_framing=data.get("resonance_framing", ""),
        scout_priorities=data.get("scout_priorities", []),
        opening_move=data.get("opening_move", "")
    )

    return report


def save_advisory(report: AdvisoryReport) -> Path:
    """
    Save the advisory report to the reports/ directory.

    Returns:
        Path to the saved Markdown file
    """
    industry_dir = REPORTS_BASE / report.industry_slug
    industry_dir.mkdir(parents=True, exist_ok=True)

    date_str = datetime.now().strftime("%Y%m%d_%H%M")
    output_path = industry_dir / f"advisory_{date_str}.md"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report.markdown)

    return output_path
