"""
📊  Report Generator — Smart Scout Audit Output Module
=======================================================
Vayne Consulting — Smart Scout Multi-Industry Edition

Saves per-target audit results and run summaries in both
Markdown and JSON formats to the reports/ directory.

Structure:
  reports/
  └── {industry_slug}/
      ├── advisory_{date}.md          ← Pre-flight brief (from advisor.py)
      ├── audit_{date}.json           ← Full machine-readable audit data
      └── audit_{date}_summary.md     ← Human-readable audit summary

Usage:
    from report_generator import save_audit_run, AuditResult

    results = [AuditResult(...), AuditResult(...)]
    paths = save_audit_run(results, industry_slug="law_firms")
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Optional

REPORTS_BASE = Path(__file__).parent / "reports"


@dataclass
class AuditResult:
    """
    Structured result for a single target audit.
    This is the core data unit produced by industry_scout.py.
    """
    # Target info
    url: str
    domain: str
    industry: str
    industry_slug: str

    # Technical checks
    status_code: int = 0
    load_time_sec: float = 0.0
    has_ssl: bool = False
    mobile_friendly: bool = False

    # Content analysis
    company_name: str = ""
    first_name: str = ""
    contact_email: str = ""
    contact_tier: int = 3               # 1=best, 3=fallback

    # LLM analysis
    insight: str = ""                   # Industry-aware hero section insight
    detected_issues: list[str] = field(default_factory=list)

    # Scoring
    base_score: int = 0                 # 1–10 from technical checks
    industry_score_bump: int = 0        # Bonus from industry-specific indicators
    final_score: int = 0                # base_score + industry_score_bump (capped at 10)

    # Output
    email_draft: str = ""               # Ready-to-review outreach draft
    status: str = "ok"                  # "ok", "failed", "skipped"
    error: Optional[str] = None

    def to_dict(self) -> dict:
        return asdict(self)

    @property
    def priority_label(self) -> str:
        if self.final_score >= 8:
            return "🔴 HIGH"
        elif self.final_score >= 5:
            return "🟡 MEDIUM"
        else:
            return "🟢 LOW"

    def to_markdown_row(self) -> str:
        """Single-line markdown table row for the summary report."""
        return (
            f"| {self.priority_label} | [{self.domain}]({self.url}) | "
            f"{self.company_name or '—'} | {self.final_score}/10 | "
            f"{self.contact_tier} | {'; '.join(self.detected_issues[:2]) or '—'} |"
        )


def _render_summary_markdown(
    results: list[AuditResult],
    industry_name: str,
    run_date: str
) -> str:
    """Render a human-readable markdown summary of an audit run."""

    total = len(results)
    ok = [r for r in results if r.status == "ok"]
    failed = [r for r in results if r.status == "failed"]
    high_priority = [r for r in ok if r.final_score >= 8]
    medium_priority = [r for r in ok if 5 <= r.final_score < 8]
    tier1 = [r for r in ok if r.contact_tier == 1]

    # Sort by score descending
    ok.sort(key=lambda r: r.final_score, reverse=True)

    rows = "\n".join(r.to_markdown_row() for r in ok)

    return f"""# 📋 Smart Scout Audit Summary
## Industry: {industry_name}
**Run Date**: {run_date}

---

## Stats

| Metric | Value |
|:---|:---|
| Total Targets | {total} |
| Successfully Audited | {len(ok)} |
| Failed / Unreachable | {len(failed)} |
| 🔴 High Priority Leads | {len(high_priority)} |
| 🟡 Medium Priority Leads | {len(medium_priority)} |
| Tier 1 Contacts (Named) | {len(tier1)} |

---

## Audit Results (sorted by priority)

| Priority | Domain | Company | Score | Contact Tier | Top Issues |
|:---|:---|:---|:---|:---|:---|
{rows}

---

## High Priority Leads — Email Drafts Ready

"""  + "\n\n---\n\n".join(
        f"### {r.company_name or r.domain}\n"
        f"**Score**: {r.final_score}/10 | **Contact Tier**: {r.contact_tier}\n\n"
        f"**Issues Detected**: {', '.join(r.detected_issues)}\n\n"
        f"**Insight**: {r.insight}\n\n"
        f"```\n{r.email_draft}\n```"
        for r in high_priority[:10]
    ) + f"""

---
*Generated by Smart Scout — Vayne Consulting Liquidity Acceleration Tool*
"""


def save_audit_run(
    results: list[AuditResult],
    industry_slug: str,
    industry_name: str = ""
) -> dict[str, Path]:
    """
    Save a completed audit run to the reports directory.

    Returns:
        Dict with keys "json" and "markdown" pointing to saved file paths.
    """
    industry_dir = REPORTS_BASE / industry_slug
    industry_dir.mkdir(parents=True, exist_ok=True)

    date_str = datetime.now().strftime("%Y%m%d_%H%M")
    run_date = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Save JSON (full data)
    json_path = industry_dir / f"audit_{date_str}.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "industry": industry_name or industry_slug,
                "industry_slug": industry_slug,
                "run_date": run_date,
                "total_targets": len(results),
                "results": [r.to_dict() for r in results]
            },
            f,
            indent=2,
            ensure_ascii=False
        )

    # Save Markdown summary
    md_path = industry_dir / f"audit_{date_str}_summary.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(_render_summary_markdown(results, industry_name or industry_slug, run_date))

    return {"json": json_path, "markdown": md_path}
